### ISSUE TITLE
Authentication for Jenkins CLI

### ISSUE THREAD

**Issue by takluyver** [ipython/ipython-ansible-jenkins#5]
The Jenkins role we use is increasingly broken, and I can currently only run this with some local modifications - I don't understand ansible or Jenkins well enough to automate setting up an SSH key with Jenkins, or to feel confident turning the security off. See https://github.com/ICTO/ansible-jenkins/issues/21 .

Maybe we should switch to a different Jenkins role? There are [several on Ansible galaxy](https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=Jenkins), but it's not immediately obvious to me which to are worth investing time in experimenting with.

**Comment by minrk** [comment]
We could also conceivably drop our Jenkins instance. We mainly use it for:

1. Windows tests (but not really anymore), which is now largely addressed by AppVeyor
2. combined testing of repos, which we can probably do with less management with a dedicated repo and the new travis cron jobs.

**Comment by minrk** [comment]
I put up a test repo that replicates jack-of-none and traitlets-master-downstream-stable: https://github.com/minrk/test-grid

Adding a combination to test can be as simple as creating a new directory with a requirements.txt, or a requirements.txt and a test.sh if less than all of the tests want to be run.

Right now, there's an uninteresting failure in `jack-of-none` because of a change in IPython master causing a widgets test to fail (the change in behavior is deliberate, the test just needs updating).

**Comment by takluyver** [comment]
Thanks Min, that sounds like a better idea than keeping Jenkins up to date. Do you want to move that to the Jupyter Github org?

@jhamrick there's an nbgrader job on Jenkins as well, but it looks like it hasn't run in 6 months. Do you still want anything from that before we shut the Jenkins server down?

**Comment by jhamrick** [comment]
Nope, I'm no longer using Jenkins for nbgrader so it's fine to shut it down.

**Comment by minrk** [comment]
test-grid's up at https://github.com/jupyter/test-grid. Anything we should do before shutting down Jenkins?

**Comment by takluyver** [comment]
I don't think so. I'll shut it down early next week, since I said in my email to the list that we'd leave it a week.

We could in theory try to store the logs and redirect the URLs to point to them in static form, but I don't think it's worth the effort of setting that up to avoid breaking a relatively small number of links.
